# Generated by Django 6.0.7 on 2026-08-05 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_add_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_type',
            field=models.CharField(choices=[('Full-Time', 'دوام كامل'), ('Part-Time', 'دوام جزئي'), ('Fixed-Term', 'عقد محدد المدة'), ('Internship', 'تدريب')], default='Full-Time', max_length=20),
        ),
    ]
