# Generated by Django 6.0.7 on 2026-08-06 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_first_name_employee_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='temporary_password',
            field=models.CharField(blank=True, help_text='كلمة المرور المؤقتة للاستخدام الداخلي فقط', max_length=100, null=True),
        ),
    ]
