# Generated by Django 6.0.7 on 2026-08-13 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_employee_address_employee_date_of_birth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeePhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('label', models.CharField(blank=True, default='Mobile', max_length=50, verbose_name='التسمية')),
                ('is_primary', models.BooleanField(default=False, verbose_name='رقم رئيسي')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='employees.employee')),
            ],
            options={
                'ordering': ['-is_primary', 'id'],
                'unique_together': {('employee', 'number')},
            },
        ),
    ]
