# Generated by Django 6.0.7 on 2026-08-19 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_employeephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='clearance_status',
            field=models.CharField(choices=[('PENDING', 'قيد الإخلاء'), ('IN_PROGRESS', 'قيد التنفيذ'), ('CLEARED', 'مكتمل')], default='PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='contract',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='contracts/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='contract',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'نشط'), ('EXPIRED', 'منتهي'), ('TERMINATED', 'منتهٍ'), ('RESIGNED', 'استقالة')], default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='contract',
            name='termination_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='termination_reason',
            field=models.TextField(blank=True),
        ),
    ]
