# Generated by Django 6.0.7 on 2026-08-22 22:26

from django.db import migrations, models


def assign_employee_numbers(apps, schema_editor):
    Employee = apps.get_model('employees', 'Employee')
    for number, employee in enumerate(Employee.objects.order_by('id'), start=1):
        employee.employee_number = number
        employee.save(update_fields=['employee_number'])


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_contract_clearance_status_contract_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.RunPython(assign_employee_numbers, migrations.RunPython.noop),
    ]
