# Generated by Django 6.0.7 on 2026-08-22 23:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_employee_birth_date_employee_emergency_contact_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='national_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(11), django.core.validators.MaxLengthValidator(11), django.core.validators.RegexValidator('^\\d{11}$', 'يجب أن يتكون الرقم الوطني من 11 رقم بالضبط')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(10), django.core.validators.RegexValidator('^\\d{10}$', 'يجب أن يتكون رقم الهاتف من 10 أرقام بالضبط')]),
        ),
    ]
