# Generated by Django 6.0.7 on 2026-08-06 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('employee_created', 'إنشاء موظف'), ('department_created', 'إنشاء قسم'), ('position_created', 'إنشاء مسمى وظيفي'), ('employee_updated', 'تعديل موظف'), ('department_updated', 'تعديل قسم'), ('position_updated', 'تعديل مسمى وظيفي'), ('leave_request', 'طلب إجازة'), ('leave_approved', 'موافقة على إجازة'), ('leave_rejected', 'رفض إجازة'), ('general', 'إشعار عام')], default='general', max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('unread', 'غير مقروء'), ('read', 'مقروء'), ('opened', 'مفتوح')], default='unread', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'إشعار',
                'verbose_name_plural': 'الإشعارات',
                'ordering': ['-created_at'],
            },
        ),
    ]
