# Generated by Django 6.0.7 on 2026-08-08 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'إشعار قديم', 'verbose_name_plural': 'الإشعارات القديمة'},
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SystemNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(choices=[('created', 'إنشاء'), ('updated', 'تعديل'), ('deleted', 'حذف'), ('assigned', 'تعيين'), ('submitted', 'تقديم'), ('approved', 'موافقة'), ('rejected', 'رفض')], max_length=50)),
                ('target_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('notification_type', models.CharField(choices=[('SYSTEM', 'نظام'), ('EMPLOYEE', 'موظف'), ('DEPARTMENT', 'قسم'), ('LEAVE', 'إجازة'), ('PAYROLL', 'رواتب')], default='SYSTEM', max_length=20)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_notifications', to=settings.AUTH_USER_MODEL)),
                ('target_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'إشعار نظام',
                'verbose_name_plural': 'إشعارات النظام',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='core_system_recipie_4346da_idx'), models.Index(fields=['notification_type'], name='core_system_notific_056a13_idx'), models.Index(fields=['created_at'], name='core_system_created_f66062_idx')],
            },
        ),
    ]
