# Generated by Django 6.0.7 on 2026-08-30 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_internalmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
