# Generated by Django 6.0.7 on 2026-09-19 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='internalmessage',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internalmessage',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
