# Generated by Django 6.0.7 on 2026-09-19 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_internalmessage_deleted_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internalmessage',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='internalmessage',
            name='is_deleted',
        ),
    ]
