# Generated by Django 6.0.7 on 2026-08-23 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0003_performanceevaluation_dispatch_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performanceevaluation',
            name='title',
            field=models.CharField(default='تقييم أداء', max_length=255, verbose_name='عنوان التقييم'),
        ),
    ]
