# Generated by Django 6.0.7 on 2026-09-01 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0007_position_is_head'),
        ('performance', '0004_alter_performanceevaluation_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='performanceevaluation',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='performance_evaluations', to='departments.department', verbose_name='الأقسام المستهدفة'),
        ),
    ]
