# Generated by Django 6.0.7 on 2026-09-01 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0006_performanceevaluation_evaluation_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='رمز المحور')),
                ('name', models.CharField(max_length=120, verbose_name='اسم المحور')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب')),
            ],
            options={
                'verbose_name': 'محور تقييم',
                'verbose_name_plural': 'محاور التقييم',
                'ordering': ('order', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='PerformanceQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='نص السؤال')),
                ('max_score', models.PositiveSmallIntegerField(default=5, verbose_name='الدرجة القصوى')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب')),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='التقييم')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='performance.performanceevaluation', verbose_name='التقييم')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='performance.questioncategory', verbose_name='المحور')),
            ],
            options={
                'verbose_name': 'سؤال تقييم',
                'verbose_name_plural': 'أسئلة التقييم',
                'ordering': ('order', 'pk'),
            },
        ),
    ]
