# Generated by Django 6.0.7 on 2026-09-15 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0007_position_is_head'),
        ('performance', '0008_seed_question_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان التقييم')),
                ('questions', models.JSONField(blank=True, default=list, verbose_name='الأسئلة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('departments', models.ManyToManyField(blank=True, related_name='performance_drafts', to='departments.department', verbose_name='الأقسام المستهدفة')),
            ],
            options={
                'verbose_name': 'مسودة تقييم',
                'verbose_name_plural': 'مسودات التقييم',
                'ordering': ('-updated_at',),
            },
        ),
    ]
