# Generated by Django 6.0.7 on 2026-08-13 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0005_employee_address_employee_date_of_birth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('ANNUAL', 'سنوية'), ('SICK', 'مرضية'), ('UNPAID', 'بدون راتب'), ('EMERGENCY', 'طارئة')], max_length=15, verbose_name='نوع الإجازة')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(verbose_name='تاريخ النهاية')),
                ('reason', models.TextField(verbose_name='سبب الإجازة')),
                ('status', models.CharField(choices=[('PENDING', 'قيد الانتظار'), ('APPROVED', 'مقبولة'), ('REJECTED', 'مرفوضة')], default='PENDING', max_length=10, verbose_name='حالة الطلب')),
                ('ai_prediction', models.CharField(choices=[('APPROVED', 'مقبول'), ('REJECTED', 'مرفوض'), ('PENDING', 'قيد التحليل')], default='PENDING', max_length=20, verbose_name='توصية الذكاء الاصطناعي')),
                ('ai_confidence', models.FloatField(default=0.0, verbose_name='نسبة الثقة')),
                ('manager_notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات المدير')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to='employees.employee', verbose_name='الموافق عليهم')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='employees.employee', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'طلب إجازة',
                'verbose_name_plural': 'طلبات الإجازات',
            },
        ),
    ]
