# Generated by Django 6.0.7 on 2026-08-25 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0002_leaverequest_ai_prediction_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='leave_attachments/', verbose_name='المرفق'),
        ),
    ]
