# Generated by Django 6.0.7 on 2026-08-23 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_add_bonuses_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='status',
            field=models.CharField(choices=[('PAID', 'مدفوع'), ('PENDING', 'معلق')], default='PENDING', max_length=10, verbose_name='حالة الصرف'),
        ),
    ]
