# Generated by Django 6.0.7

from decimal import Decimal

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_payroll_payment_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryAdvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مبلغ السلفة المطلوب')),
                ('months', models.PositiveIntegerField(verbose_name='مدة السداد بالشهور')),
                ('monthly_deduction', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='الاستقطاع الشهري')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='المبلغ المسدد')),
                ('reason', models.TextField(verbose_name='سبب طلب السلفة')),
                ('status', models.CharField(choices=[('PENDING', 'معلقة'), ('APPROVED', 'مقبولة'), ('REJECTED', 'مرفوضة')], default='PENDING', max_length=10, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التقديم')),
            ],
            options={
                'verbose_name': 'طلب سلفة مالية',
                'verbose_name_plural': 'طلبات السلف المالية',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='salaryadvance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_advances', to='employees.employee', verbose_name='الموظف'),
        ),
    ]