# Generated by Django 6.0.7 on 2026-09-17 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_salary_advance'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryadvance',
            name='advance_type',
            field=models.CharField(choices=[('emergency', 'سلفة طارئة'), ('marriage', 'سلفة زواج'), ('medical', 'سلفة علاجية'), ('personal', 'سلفة شخصية'), ('periodic', 'سلفة احتياجات دورية')], default='personal', max_length=20, verbose_name='نوع السلفة'),
        ),
        migrations.AddField(
            model_name='salaryadvance',
            name='deduction_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ بداية الخصم'),
        ),
    ]
