# Generated by Django 6.0.7 on 2026-09-20 16:47

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0006_salaryadvance_advance_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='health_insurance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='التأمين الصحي'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='social_insurance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='التأمينات الاجتماعية'),
        ),
    ]
