# Generated by Django 6.0.7 on 2026-08-02 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_alter_department_options_alter_position_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'قسم', 'verbose_name_plural': 'الأقسام'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'verbose_name': 'وظيفة', 'verbose_name_plural': 'الوظائف'},
        ),
        migrations.AddField(
            model_name='position',
            name='base_salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='الراتب التقديري'),
        ),
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(max_length=10, unique=True, verbose_name='رمز القسم'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='اسم القسم'),
        ),
        migrations.AlterField(
            model_name='position',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='departments.department', verbose_name='القسم'),
        ),
        migrations.AlterField(
            model_name='position',
            name='title',
            field=models.CharField(max_length=100, verbose_name='المسمى الوظيفي'),
        ),
    ]
