# Generated by Django 6.0.7 on 2026-08-04 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_alter_department_options_alter_position_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='وصف القسم'),
        ),
    ]
