# Generated by Django 6.0.7 on 2026-08-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0004_department_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='role',
            field=models.CharField(choices=[('Employee', 'موظف'), ('Manager', 'مدير'), ('HR Admin', 'مسؤول موارد بشرية')], default='Employee', max_length=100, verbose_name='الدور'),
        ),
    ]