# Generated by Django 6.0.7 on 2026-08-22 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0005_position_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='salary_max',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='الحد الأقصى للراتب'),
        ),
        migrations.AddField(
            model_name='position',
            name='salary_min',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='الحد الأدنى للراتب'),
        ),
    ]
