# Generated by Django 6.0.7 on 2026-09-15 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0007_position_is_head'),
        ('employees', '0014_employee_personal_email_phone_secondary'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_department', to='employees.employee', verbose_name='مدير القسم'),
        ),
    ]
