# Generated by Django 6.0.7 on 2026-08-31 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('check_in', models.DateTimeField(blank=True, null=True, verbose_name='وقت الدخول')),
                ('check_out', models.DateTimeField(blank=True, null=True, verbose_name='وقت الخروج')),
                ('status', models.CharField(choices=[('حاضر', 'حاضر'), ('تأخير', 'تأخير'), ('غائب', 'غائب')], default='حاضر', max_length=20, verbose_name='الحالة')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'سجل الحضور',
                'verbose_name_plural': 'سجلات الحضور',
                'ordering': ['-date', '-check_in'],
            },
        ),
    ]
